module.exports = {
  components: {
    categories: [
      {
        name: "TypeScript components",
        include: [
          "src/components/BulletedList/BulletedList.tsx",
          "src/components/BulletedListItem/BulletedListItem.tsx",
          "src/components/Sidenav/Sidenav.tsx",
          "src/components/SidenavGroup/SidenavGroup.tsx",
          "src/components/SidenavLink/SidenavLink.tsx",
          "src/components/SidenavSection/SidenavSection.tsx",
          "src/components/SidenavTitle/SidenavTitle.tsx",
          "src/components/ApplicationLayout/ApplicationLayout.tsx",
          "src/components/Header/Header.tsx",
          "src/components/Button/Button.tsx",
          "src/components/Card/Card.tsx",
          "src/components/Accordion/Accordion.tsx",
          "src/components/Icon/Icon.tsx",
          "src/components/Wizard/Wizard.tsx",
          "src/components/Inset/Inset.tsx",
          "src/components/Tabs/Tabs.tsx",
          "src/components/ToggleGroup/ToggleGroup.tsx",
          "src/components/TextInput/TextInput.tsx",
          "src/components/Spinner/Spinner.tsx",
          "src/components/Checkbox/Checkbox.tsx",
          "src/components/Chip/Chip.tsx",
          "src/components/Flex/Flex.tsx",
          "src/components/Select/Select.tsx",
          "src/components/Heading/Heading.tsx",
          "src/components/Textarea/Textarea.tsx",
          "src/components/Tag/Tag.tsx",
          "src/components/Table/Table.tsx",
          "src/components/Switch/Switch.tsx",
          "src/components/Slider/Slider.tsx",
          "src/components/ResultsetTable/ResultsetTable.tsx",
          "src/components/RadioGroup/RadioGroup.tsx",
          "src/components/QuickNav/QuickNav.tsx",
          "src/components/ProgressBar/ProgressBar.tsx",
          "src/components/PasswordInput/PasswordInput.tsx",
          "src/components/Paragraph/Paragraph.tsx",
          "src/components/Paginator/Paginator.tsx",
          "src/components/NumberInput/NumberInput.tsx",
          "src/components/NavTabs/NavTabs.tsx",
          "src/components/Link/Link.tsx",
          "src/components/Header/Header.tsx",
          "src/components/Footer/Footer.tsx",
          "src/components/FileInput/FileInput.tsx",
          "src/components/Dropdown/Dropdown.tsx",
          "src/components/Dialog/Dialog.tsx",
          "src/components/DateInput/DateInput.tsx",
          "src/components/NavTabsItem/NavTabsItem.tsx",
          "src/components/Typography/Typography.tsx",
        ],
      },
      {
        name: "JS",
        include: ["src/components/ThemeCustomizer/ThemeCustomizer.js"],
      },
      {
        name: "Layout",
        include: [
          "src/components/Bleed/Bleed.tsx",
          "src/components/Box/Box.tsx",
          "src/components/ApplicationLayout/ApplicationLayout.tsx",
        ],
      },
    ],
    wrapper: "src/components/UXPinWrapper/UXPinWrapper.js",
    webpackConfig: "webpack.config.js",
  },
  name: "DXC Halstack Design System",
};
